project:
  type: website
  output-dir: docs

website:
  title: "The University of British Columbia"
  navbar:
    left:
      - href: index.qmd
        text: Home

  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Slides"
        contents:
          - slides/MEDI504-basic-biostats-2024.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
